- hosts: localhost
  become: yes
  tasks:
    # For non-Gnome Desktop environments
    - name: Install gnome-terminal
      apt:
        name: gnome-terminal
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"

    # Uninstall Docker Desktop for Linux
    - name: Uninstall Docker Desktop
      apt:
        name: docker-desktop
        state: absent
      when: ansible_facts['distribution'] == "Ubuntu"

    # Set up Docker apt repository
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Add Docker GPG key
      # '>' is used for execution
      shell: >
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Set permissions on Docker GPG key
      command: "sudo chmod a+r /etc/apt/keyrings/docker.gpg"
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Add the repository to apt sources
      shell: >
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: update apt cache
      apt:
        update_cache: yes
      when: ansible_facts['distribution'] == "Ubuntu"

    # Installing Docker  
    - name: Install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"

    # Install yum-utils
    - name: Install yum-utils
      yum:
        name: yum-utils
        state: present
      when: ansible_facts['distribution'] == "Centos"
      
    # Add the repository
    - name: Add the repository
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      when: ansible_facts['distribution'] == "Centos"

    - name: update yum cache
      yum:
        update_cache: yes
      when: ansible_facts['distribution'] == "Centos"

    # Install Docker 
    - name: Install docker
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
      when: ansible_facts['distribution'] == "Centos"
    
    # start Docker service
    - name: Start Service
      service:
        name: docker
        state: started
        enabled: yes